### PR TITLE
Open source attribution/About screen

### PR DESCRIPTION
**Pull request by kvithayathil**
- Added an "About" screen that will also display the open source attributions.

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Looks good! But can you use the new Jetpack Navigation library instead of manually having the on click handler. That's what I'm currently using.

**Comment by kvithayathil** [comment]
I was looking into doing that but wasn't sure how to adapt it as I'm using a library with a custom builder to configure the screen

**Comment by kvithayathil** [comment]
Hmm actually, I might have a way...I'll get back to you on that 👍

**Comment by TheHollidayInn** [comment]
Sweet. How about using a different lib or event, creating an about page fragment with other info? Links to the forum, slack channel and then initialized the builder class there.

**Comment by MostafaGazar** [comment]
Closing for now, feel free to reopen after fixing the conflicts

**Pull request closed without merging**
